### ISSUE TITLE
V3.1, linker error with MySensors sketch

### ISSUE THREAD

**Issue by WestCat** [jantje/arduino-eclipse-plugin#538] opened 2016-09-27 07:07 UTC
Hey
I get a bunch of "multiple definition of" errors when I try to build on of the examples from the MySensors library.
I have install a fresh version of the V3.1_linux64.2016-08-03_16-31-05.
Steps:
1. Create a new workspace (So I don't make any mesh with old workspaces).
2. Create a new project, select Arduino UNO board, select Sample sketch, Selected DimmableLEDActuator.
3. Added the "-DMY_RADIO_NRF24" to the properties->Arduino->Compile Options, append to C and C++.
4. Made a resource filter: Exclude all, Files and Folders, recursive, Filter Details = examples* (else I get an error from the examples that is include in the AES folder under MySensors library.
5. Build the project and I get, this is just some of them:
`./.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
./libraries/MySensors/core/MyTransportNRF24.cpp.o (symbol from plugin): In function `transportInit()':
(.text+0x0): multiple definition of `transportReceive(void*)'
./.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
./libraries/MySensors/core/MyTransportNRF24.cpp.o (symbol from plugin): In function `transportInit()':
(.text+0x0): multiple definition of `transportPowerDown()'
./.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Test.elf] Error 1`

I really hope that some can help me because I don't like to use the Arduino IDE for editing my code.

Thanks
Thomas

**Comment by jantje** [comment] 2016-09-27 12:48
Thanks for this really nicely documented issue.
The documentation of the steps and what you already did makes it easier for me to understand what is going on. 

1) that is the way to go (both on how to do and on how to document a issue)
2) that is the way to go (both on how to do and on how to document a issue)
3) is caused by know limitation https://github.com/jantje/arduino-eclipse-plugin/issues/478 and you applied the correct work around
4) is fixed in the nightly https://github.com/jantje/arduino-eclipse-plugin/issues/522 but if you want to stay with your current version you applied the correct work around
5) I think this is caused by know limitation; https://github.com/jantje/arduino-eclipse-plugin/issues/271
The people of Mysensors applied the workaround https://github.com/mysensors/MySensors/blob/development/MySensors.h#L25
I don't know if they released this already.

So I am closing this issue as a duplicate.
Thanks again for the well documented issue

**Closed by jantje** 2016-09-27 12:48 UTC
