### ISSUE TITLE
Create a new Sketch with Ariadne fails using V3 

### ISSUE THREAD

**Issue by stephanmarks** [jantje/arduino-eclipse-plugin#449] opened 2016-05-12 16:18 UTC
I have add the Location https://per1234.github.io/Ariadne-Bootloader/package_codebendercc_ariadne-bootloader_index.json. Than I chose under Platforms and Boards the Ariadne-Booloader 1.0.2 

If I try to create a new Sketch for 
Board: Atmega328P(Uno/Mini/Duemilanove/etc.)
Model: Nano
Clock: 16MHZ Full Swing
Board Configuration Ethernet Shield, Blink

If I click finish I got a failure
failed to find core reference: arduino:arduino 

Error-Log
[Error-Log.txt](https://github.com/jantje/arduino-eclipse-plugin/files/261778/Error-Log.txt)

**Comment by jantje** [comment] 2016-05-12 16:28
this is a duplicate of #421

**Closed by jantje** 2016-05-12 16:28 UTC
Labels: status: duplicate
