### ISSUE TITLE
duplicate icons

### ISSUE THREAD

**Issue by cho934** [jantje/arduino-eclipse-plugin#508] opened 2016-07-27 09:45 UTC
Hi, I'm trying now to use v3, but idem to v2, sometimes when I open Eclipse (Luna or Mars), all arduino icons are duplicated on all perpective again and again. Very strange, and very annoying.

If I customize the perspective, I can only see each icon but without duplication, If I remove all of them, all icons disappear, but if I add some of them, each icon keep duplicated.

What's wrong ?

**Comment by rlogiacco** [comment] 2016-07-27 09:52
Can you please specify which version exactly are you installing? 
I believe you are speaking of the plugin and not of the bundled product, but is it the stable version or the nightly? And which version of the nightly, eventually?

**Comment by cho934** [comment] 2016-07-27 09:59
Eclipse Luna and I had Arduino Eclipse plugin version 2. 
I'm working on a virtual machine with CUbuntu 14.04.
I've just migrate Eclipse to Mars.2 and installed Arduino Eclipse plugin version 3. 
But I've just noticed that the plugin version 2 is always there also. So the Bug from version 2 is always there... 
I will uninstall all versions and install only v3.

**Comment by cho934** [comment] 2016-07-27 10:07
If I uninstall all then reinstall V3 plugin from Eclipse Market place, V2 is also installed and the problem of duplicate icons is always there...

![arduino_plugin_duplicate_icons](https://cloud.githubusercontent.com/assets/6328976/17171810/93041da4-53f2-11e6-942b-b214ae951146.png)

**Comment by jantje** [comment] 2016-07-27 13:02
If you have V2 and V3 installed it is normal that you have the icons double.

**Comment by cho934** [comment] 2016-07-29 10:21
As soon as I installed V3, V2 is also installed using the market place. If I understand your remark, it is in fact a problem...

**Comment by jantje** [comment] 2016-07-29 11:23
V2 and V3 have a different update site and V3 is marked as an update of V2 and you are the first one to report this problem. So there must be some "difference" between "your system" and "my system"
Have you activated oomph
Do you have the same problem with the product?

**Comment by jantje** [comment] 2016-08-20 11:12
@cho934 Have you been able to find the root cause?

**Comment by jantje** [comment] 2016-09-03 21:25
Closing as user error due to lack of input.

**Closed by jantje** 2016-09-03 21:25 UTC
Labels: status: usage error, status: waiting for input
