### ISSUE TITLE
V3.0 and V3.1 do not install standard Arduino tools (i.e. GCC)

### ISSUE THREAD

**Issue by edogaldo** [jantje/arduino-eclipse-plugin#543] opened 2016-10-07 13:04 UTC
Neon.1, installed via "Install new software" feature.
In the "eclipse\cpp-neon\eclipse\arduinoPlugin\tools" folder I can find only subfolder "make".
There is no "arduino" subfolder...

**Comment by edogaldo** [comment] 2016-10-07 14:29
Note: switching the platform version (i.e. from 1.6.14 to 1.6.11 and then back to 1.6.14) installed the missing tools.

**Comment by jantje** [comment] 2016-10-07 16:37
Do you have logs that may show what went wrong?
Didn't you get an error your path is to deep? (windows still has a maximum path depth)

**Comment by edogaldo** [comment] 2016-10-07 16:59
Where could I find logs?
The fact that switching the version solved the problem tells me it shouldn't be due to the path length..

**Comment by jantje** [comment] 2016-10-07 17:47
>Where could I find logs?
The fact that switching the version solved the problem tells me it shouldn't be due to the path length..

It does not tell me this.

The process you describe (what you call switching) are actually 4 completely separate actions.
Deinstall 1.6.14 install 1.6.11 deinstall 1.6.12 and install 1.6.14. I'm not even sure it will happen in this order. 

Have you tried to add hardware to the plugin by copying files in [Eclipse install]/ArduinoPlugin?
If so it is normal Arduino wil not be installed as these are only installed if no boards are available.

**Comment by edogaldo** [comment] 2016-10-07 18:05
This has nothing to do with issue #545
I was performing first installation of the v3 plugin on a fresh eclipse (neon) installation.
After installing the plugin the arduino subfolder (the one containing the avr-gcc) was missing and I could not compile.
Even uninstalling and reinstalling the plugin added the missing subfolder..

**Comment by edogaldo** [comment] 2016-10-07 18:07
Even uninstalling and reinstalling the plugin did not add the missing subfolder..

**Comment by jantje** [comment] 2016-10-07 18:55
>Even uninstalling and reinstalling the plugin did not add the missing subfolder..

This will do nothing indeed.

**Comment by jantje** [comment] 2016-10-29 22:56
Did you install from the nightly?
If so this is probably a duplicate of #551

**Comment by jantje** [comment] 2016-11-01 23:05
I have seen that the error handling in this part of the code is not quite good. I fixed this in V4 #570.
I assume something went wrong on your system and it did not get reported.
So I propose to close this one.

**Closed by jantje** 2016-11-01 23:05 UTC
