### ISSUE TITLE
make: *** [subdir.mk:20: esp8266cpptest.cpp.o] Error 2 

### ISSUE THREAD

**Issue by Seppeltronics** [jantje/arduino-eclipse-plugin#617] opened 2017-01-01 00:13 UTC
Hello,

I downloaded the latest version and tried to compile an empty(just Cpp and H File) project, but got an error message, but I have no idea why. I already removed the paths of mingw and msys as this post on stackoverflow suggests: [http://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified](url)

I tried a Project for Duemillanove, no problems at all, but ESP8266 is not working.

Does anyone know how to fix it or is it a Bug?

Thank you very much,

Seppel

---------------------------------------------------------
System: Pentium i5, Windows 7 64 Bit
Used Software: V3.1_win64.2016-08-03_16-31-05.tar.gz

------------------------------------------------------------
Message:

00:48:26 **** Incremental Build of configuration Release for project esp8266cpptest ****
"C:\\eclipse\\eclipseArduino\\sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ../esp8266cpptest.cpp'
'Starting C++ compile'
"C:\eclipse\eclipseArduino\sloeber\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/eclipse/eclipseArduino/sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266  -I"C:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\cores\esp8266" -I"C:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\variants\nodemcu" -MMD -MP -MF"esp8266cpptest.cpp.d" -MT"esp8266cpptest.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "../esp8266cpptest.cpp" -o "esp8266cpptest.cpp.o"  -Wall
process_begin: CreateProcess(NULL, C:\eclipse\eclipseArduino\sloeber\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -IC:/eclipse/eclipseArduino/sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266 -IC:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\cores\esp8266 -IC:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\variants\nodemcu -MMD -MP -MFesp8266cpptest.cpp.d -MTesp8266cpptest.cpp.o -D__IN_ECLIPSE__=1 -x c++ ../esp8266cpptest.cpp -o esp8266cpptest.cpp.o -Wall, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [subdir.mk:20: esp8266cpptest.cpp.o] Error 2

00:48:30 Build Finished (took 4s.113ms)

**Comment by jantje** [comment] 2017-01-01 01:40
```
process_begin: CreateProcess(NULL, C:\eclipse\eclipseArduino\sloeber\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -IC:/eclipse/eclipseArduino/sloeber/arduinoPlugin/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10609 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266 -IC:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\cores\esp8266 -IC:\eclipse\eclipseArduino\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\variants\nodemcu -MMD -MP -MFesp8266cpptest.cpp.d -MTesp8266cpptest.cpp.o -D__IN_ECLIPSE__=1 -x c++ ../esp8266cpptest.cpp -o esp8266cpptest.cpp.o -Wall, ...) failed.
make (e=2): The system cannot find the file specified.
```
Here you see make tries to execute a command with parameters. This is typically caused by bad quoting.
I have fixed many thing in this area in V4 (not yet released as a stable) It rings a bell but I can't recall what was the issue.


As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Closed** 2017-01-01 12:35 UTC
